### ISSUE TITLE
Consider renaming repo to `cnc-go`

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/go-cnc#2]
Bikeshedding

**Comment by tzdybal** [comment]
I did some research on this, and it's completely inconsistent - even google has repositories with both `go-` prefix and `-go` suffix.

Honorable mentions:
libp2p/go-libp2p
ethereum/go-ethereum
google/go-cloud

kubernetes/client-go
cosmos/ibc-go

I think that prefix is more common.
